###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)  
spring:
  application:
    name: app-mayikt-weixin
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 1
        max-wait: -1
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wxdac4e797308fecc9 #（一个公众号的appid）
        secret: 8c0fce48f245db4deb385a0992b8ac4b #（公众号的appsecret）
        token: czktWx #（接口配置里的Token值）

mayikt:
  weixin:
    registration:
      code:
     ###微信注册码消息
        message:  您的注册码为:%s，请关注<a href="https://ke.qq.com/course/273548">郴州科泰</a>，<a href='https://jq.qq.com/?_wv=1027&k=5TVfAMF'>3294520165</a>，期待你的加入，感谢！
      ###默认提示消息
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!

####swagger相关配置
swagger:
  base-package: com.mayikt.weixin.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由每特教育|蚂蚁课堂版权所有，未经过允许的情况下，私自分享视频和源码属于违法行为。
  version: 1.1
  terms-of-service-url: www.mayikt.com
  contact:
    name: 97后互联网架构师-余胜军
    email: 644064779@qq.com

